### ISSUE TITLE
Videos 404 not found in subdirectories or renamed upload directory

### ISSUE THREAD

**Issue by fl0schi** [ShaneIsrael/fireshare#102]
Dear Team,

**Describe the bug**
I'm facing issues with playing videos if they're not in the default upload directory or if they're in subdirectories.
See in the Screenshot attached, it looks like Fireshare is not able to locate the video file if it's in a subdirectory or if the upload path is change to another name (via settings; and ofc video uploaded after changing this name).

**To Reproduce**
1. Start the container with the following settings..
3. Login as admin
5. Create Subdirectories on the server or change the admin upload folder via WebGUI
7. Upload a video via WebGUI or place a video (mp4 file in my tests) in a subdirectorie

**Docker config:**
```bash
docker run -d \
  --name fireshare \
  --restart=always \
  --label=com.centurylinklabs.watchtower.enable=true \
  -v /run/user/1000/docker.sock:/run/user/1000/docker.sock \
  -v /share/fireshare/data:/data:rw \
  -v /share/fireshare/processed:/processed:rw \
  -v /share/fireshare/videos:/videos:rw \
  -p 127.0.0.1:8090:80 \
  -e ADMIN_PASSWORD=mysupersecurepassword \
  -e MINUTES_BETWEEN_VIDEO_SCANS=1 \
  shaneisrael/fireshare:latest
```
_Note: I'm using a rev proxy outside of docker to connect via https to all those webserivces. So the revproxy is hosting the secure connections and forwards the traffic to the local mapped system port which is connected with docker.
Also my docker runs in the context of a service user without root privileges; this user owns the whole /share/fireshare directory._

**Expected behavior**
Like described I would like to see those subdirectories as a "filter" in the Dropdown menu.

**Screenshots**
_![issue-fireshare_notfound](https://user-images.githubusercontent.com/62054501/176946332-d94c362e-db60-4077-8455-87b9d6b2b75d.png)_

**Desktop (please complete the following information):**
- Browser: tested with Vivaldi 5.3.2679.61 (Stable channel) (arm64) 
- Browser: tested with Firefox 101.0.1 (64-bit)

**Additional context**
I tried to rename the folders, without spaces but also that was without success.
Btw using the default upload directory (uploads) and then copy a video to a subdirectory and delete it via webgui also shows "not found" afterwards. Just tested this case, to be sure there's no permission issue..

Thanks in advance for your help!
If more information is needed, please let me know.

Br
Flo

**Comment by ShaneIsrael** [comment]
@fl0schi 
If you change a videos location after it has been scanned into the database then Fireshare doesn't know where it is at. That's why you are seeing these 404's.

At the moment we don't yet have a system in place for Fireshare to automatically re-discover where your files are at if you moved them. What you'll need to do is either delete the fireshare db file that is located in your fireshare data folder and re-start the application. 

OR if its only a couple files, delete the files from the WebUI (so long as you moved them from their scanned in position so that the actual files don't also get deleted. ) and that will also delete the database data for it.

This is something I want to remedy and just need to figure out a proper way for Fireshare to detect changes and update its database to reflect the new locations.

**Comment by ShaneIsrael** [comment]
Also, empty folders will not show up in the filter. The filter is created based on paths to existing files. So once you have files on those new folders you made and those files were scanned in then you should see them show up in that filter. 

Keep in mind, only the top most level folder will show up in the filter.

**Comment by fl0schi** [comment]
@ShaneIsrael 
alright - so I just deleted the db.sqlite file in the data path and restarted the application.
After that I logged in and the library was empty (what's okay...because there're no links in the db). I triggered a manual scan and my video showed up.
Unfortunately, it's still 404 not found.

And this is also the same if I Upload a video to the filesystem directly; scan the library and try to watch it - but only if it's in a subdirectory of my "videos".

**Comment by ShaneIsrael** [comment]
Hmm, the only thing I can think that would be causing 404's after doing that would be a configuration in your reverse proxy. Are the 404's coming from your reverse proxy or are they coming from the nginx service within Fireshare? 

Can you view the Fireshare container logs while trying to access one of the videos? If you don't see any 404 errors in those logs its likely a configuration issue with your reverse proxy.

**Comment by fl0schi** [comment]
First of all - thanks for you assistance and also the fast reply. :-)
About the Logs, that's strange - within the container in the default path `/var/log/nginx` the access and error logfile are both empty. Are you storing them in a different location?

In my revproxy log it's like this:
```

<myip> - - [01/Jul/2022:20:48:35 +0200] "GET / HTTP/1.1" 200 6172 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
<myip> - - [01/Jul/2022:20:48:36 +0200] "GET /api/config HTTP/1.1" 200 5637 "https://<myurl>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
<myip> - - [01/Jul/2022:20:48:36 +0200] "GET /api/loggedin HTTP/1.1" 200 5559 "https://<myurl>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
<myip> - - [01/Jul/2022:20:48:36 +0200] "GET /static/css/main.694577ae.css.map HTTP/1.1" 200 15624 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
<myip> - - [01/Jul/2022:20:48:36 +0200] "GET /api/loggedin HTTP/1.1" 200 287 "https://<myurl>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
<myip> - - [01/Jul/2022:20:48:36 +0200] "GET /api/videos?sort=updated_at+desc HTTP/1.1" 200 601 "https://<myurl>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
<myip> - - [01/Jul/2022:20:48:36 +0200] "GET /static/js/main.3761539d.js.map HTTP/1.1" 200 3435581 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"

<myip> - - [01/Jul/2022:20:48:36 +0200] "GET /_content/derived/bbbc3bd73004ffe721cebed4ee231273/poster.jpg HTTP/1.1" 404 827 "https://<myurl>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"

<myip> - - [01/Jul/2022:20:48:37 +0200] "GET /api/video/details/bbbc3bd73004ffe721cebed4ee231273 HTTP/1.1" 200 559 "https://<myurl>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
<myip> - - [01/Jul/2022:20:48:37 +0200] "GET /_content/video/bbbc3bd73004ffe721cebed4ee231273.mp4 HTTP/1.1" 404 827 "https://<myurl>/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.136 Safari/537.36"
```

And the config is quite simple and straight forward:
```
<VirtualHost *:80>
  ProxyPreserveHost On
  ProxyRequests Off

  ServerAdmin admin@domain.tld
  ServerName <myurl>
  ServerAlias <myalias>

  ErrorLog ${APACHE_LOG_DIR}/container-fireshare-error.log
  CustomLog ${APACHE_LOG_DIR}/container-fireshare-access.log combined

  # forward traffic to container, locally
        ProxyPass / http://127.0.0.1:8090/
        ProxyPassReverse / http://127.0.0.1:8090/

  # Disable ModSecurity to fireshare work prop.
      # VIDEOS
      SecRuleRemoveById 958291             # Range Header Checks
      SecRuleRemoveById 981203             # Correlated Attack Attempt
      # GENERAL
      SecRuleRemoveById 960017             # Host header is a numeric IP address
      SecRuleRemoveById 920350
      SecRuleRemoveById 200004

RewriteEngine on
RewriteCond %{SERVER_NAME} =<myurl> [OR]
RewriteCond %{SERVER_NAME} =<myalias>
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
  ProxyPreserveHost On
  ProxyRequests Off

  ServerAdmin admin@domain.tld
  ServerName <myurl>
  ServerAlias <myalias>

  ErrorLog ${APACHE_LOG_DIR}/container-fireshare-error.log
  CustomLog ${APACHE_LOG_DIR}/container-fireshare-access.log combined

  # forward traffic to container, locally
        ProxyPass / http://127.0.0.1:8090/
        ProxyPassReverse / http://127.0.0.1:8090/

  # Disable ModSecurity to fireshare work prop.
        # VIDEOS
        SecRuleRemoveById 958291             # Range Header Checks
        SecRuleRemoveById 981203             # Correlated Attack Attempt
        # GENERAL
        SecRuleRemoveById 960017             # Host header is a numeric IP address
        SecRuleRemoveById 920350
        SecRuleRemoveById 200004

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/<myurl>/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/<myurl>/privkey.pem
</VirtualHost>
```
_Note: maybe there's no need to disable some of the Rules for ModSecurity - I just added them as well from my Cloud (also sharing videos there)._

**Comment by ShaneIsrael** [comment]
Your reverse proxy looks fine.

Just do this in a terminal. 

```
docker ps
```
grab the container id. 

```
docker logs -f <container-id>
```
Do you see any 404s come up or any GET logs showing up? Or really any errors.

**Comment by ShaneIsrael** [comment]
Just in case here is what the demo sites videos folder looks like.
![image](https://user-images.githubusercontent.com/1677199/176956163-3bc7c3f5-7f3f-478c-afa8-6455b3abc5e7.png)

```
/files/highlights:/videos:rw
```
I even have videos multiple sub-folders deep. For example
![image](https://user-images.githubusercontent.com/1677199/176956371-8c6bf848-052d-452a-a453-8cb182c4d7bb.png)

Which shows up like this in the returned video list in your network data if you look at the network tab in your browser. 
![image](https://user-images.githubusercontent.com/1677199/176956565-01d801e7-a94d-4449-a9a3-a57086e63688.png)

Which we can view by going to the video_id in that screenshot. 
video_id: b06dcdd8070fe18ebb1f10e4b1cdc7f8

https://v.fireshare.net/#/w/b06dcdd8070fe18ebb1f10e4b1cdc7f8
or directly via
https://v.fireshare.net/_content/video/b06dcdd8070fe18ebb1f10e4b1cdc7f8.mp4

So as you can see, files within subfolders is working. The only thing I can think of in your scenario is something network related that is not allowing these `_content` paths to get to the Fireshare container.

**Comment by fl0schi** [comment]
Buddy I think we found it...
```
2022/07/01 19:14:30 [error] 11#11: *4 open() "/processed/video_links/bbbc3bd73004ffe721cebed4ee231273.mp4" failed (2: No such file or directory), client: 172.31.255.1, server: default, request: "GET /_content/video/bbbc3bd73004ffe721cebed4ee231273.mp4 HTTP/1.1", host: "<myurl>", referrer: "https://<myurl>/"
```

So yes, there're also the 404 errors within the container.
And it looks like I got into trouble with the manual moving **after** uploaded the files.
There're symlinks for the processed videos, right?
Those where pointing to the wrong file, deleting only the db.sqlite file didn't work out.

I deleted the db, as well as the symlinks. Restarted the application and scanned the library again..
Tadaaaa. :-D

Looks like I got into trouble while moving and then testing, of course the biggest issue was maybe that I didn't deleted the local files completely before testing again with a new container.
Let me do some quick tests; but I'm quite shure we can close it in few mins. 👍

**Comment by ShaneIsrael** [comment]
OH duh. Yeah that's my bad. I completely spaced that you would need to also delete the associated sym links. If you delete via the WebUI it does handle also deleting the sym links and derived data.

**Comment by ShaneIsrael** [comment]
Also, you shouldn't have to delete the local files when using a new container. The same exact id's and paths will be generated on all fireshare containers.

**Comment by fl0schi** [comment]
Got you, no worries about that and absolute my fault.
Too much in parallel and testing but not from scratch. 

Finally, I got it working with the structure I want. And for you also a confirmation it's working via apache2 as a rev proxy.

Thank you so much for the really fast feedback and assistance and ofc also for the good work here!
Have great day ahead and an awesome weekend!

Br
Flo
