### ISSUE TITLE
preview images

### ISSUE THREAD

**Issue by wangrui1573** [ShaneIsrael/fireshare#106]
The videos I upload do not have preview images by default. Will there be preview images only when I share them? How can I create preview images for all videos at once?

**Comment by ShaneIsrael** [comment]
Preview images are created automatically during each scan. So once you upload a video, you'll need to wait until the next scan happens and preview images will be generated. 

Make sure your videos are of one of the supported formats. If for some reason the images are still not showing up, check the Fireshare container logs for any errors and report back.
