### ISSUE TITLE
[Feature Request] Change username "admin"

### ISSUE THREAD

**Issue by Synt3x** [ShaneIsrael/fireshare#113]
Would be great if we could change the admin to something else on initial setup.

**Comment by truthsword** [comment]
Agree. For docker, another environmental variable would be great.

**Comment by ShaneIsrael** [comment]
I'll look into this later tonight. I may be able to add this relatively easily. We'll see.

**Comment by ShaneIsrael** [comment]
This has been added in PR #121  and will be available in the latest docker image v1.2.3
