### ISSUE TITLE
Shareable Link Domain - How does it work?

### ISSUE THREAD

**Issue by truthsword** [ShaneIsrael/fireshare#114]
I'm running a docker container and I entered a domain "share.mydomain.com" under settings.

When I log into the container over the LAN, I am using `http://192.168.1.42:12345`. When I create a link, the domain I entered is ignored, and the link comes back with my local LAN IP, so...

`http://192.168.96.101:12345/w/1a84ad8333l3l58238e7dc0f65047`

... which is not shareable outside my LAN. Instead, I was expecting:

`https://share.mydomain.com/w/1a84ad8333l3l58238e7dc0f65047`

OTOH, if I log into Fireshare using `https://share.mydomain.com`, which is redirected by reverse proxy to `http://192.168.1.42:12345`, the share links use my domain. It seems that the domain I enter in Settings is ignored. What am I doing wrong?

**Comment by ShaneIsrael** [comment]
It should be working how you are expecting. Basically if you set the shareable link domain it will override the domain in your URL when you are clicking the copy link buttons. 

So for example, if I have the shareable link domain set to "share.mydomain.com" and
with my demo if you are at on some video at -> `v.fireshare.net/w/asdfasdfadfasdf`  and click the copy buttons, the link that is copied would be `share.mydomain.com/w/asdfasdfadfasdf`

There might be a bug with it not working when you are at an address with a port. i.e http://192.168.1.42:12345
So I'll take a look at this later when I'm off from work.

**Comment by ShaneIsrael** [comment]
So I confirmed that it is working correctly. However, you may need to wait a minute for the change to take affect and you will probably need to hard reload the webpage a couple times.

**Comment by truthsword** [comment]
OK. Yes. This began working after some time. Thank you.
