### ISSUE TITLE
Open Graph Support on Android

### ISSUE THREAD

**Issue by truthsword** [ShaneIsrael/fireshare#118]
Pasted a share link on Android/Google Messages, and only see the link itself.  Not the metadata or thumbnail.

*Direct links copied from the link copy buttons in Fireshare will allow websites and messaging apps to read the open graph data and show title, description and video thumbnails in your posts. *

Instead...

![](https://i.imgur.com/TFtfvLb.png)

Suggestions?

**Comment by Shane-stage** [comment]
You need to use the link given by the copy buttons. That will give you the open graph data. OR just remove the /#/ from that url.

**Comment by truthsword** [comment]
Same result
![](https://i.imgur.com/vPfSsoi.png)

**Comment by ShaneIsrael** [comment]
Doing some googling around this looks to be a common issue with Android sms and open graph previews. There's one potential option that might work which I'll include in my next update. If that doesn't work though there may not be anything I can do since we're already providing all the open graph tags. 

![image](https://user-images.githubusercontent.com/1677199/183232469-ccadad77-4e2f-4ced-aab5-41a7d65f2b4f.png)

**Comment by ShaneIsrael** [comment]
@truthsword unfortunately the one "potential" fix I found online doesn't seem to be working. I am aware of the issue though so I'll keep an eye out for a fix but for now it looks like there isn't anything I can do about the open graph data not working on Android. Might be an issue on Androids side. 

I'm going to close this for now. But will update it if it ever gets fixed.

**Comment by truthsword** [comment]
Just FYI... but my iPhone recipients are only seeing the link as well.

**Comment by ShaneIsrael** [comment]
Are you using iMessage or sms? It's probably not going to work with sms and
I don't have a way to test iMessage.

**Comment by truthsword** [comment]
Maybe it's me misunderstanding. I SMS web links and they appear as:

![](https://i.imgur.com/ErESvTg.png)

I was expecting a similar result here.

**Comment by ShaneIsrael** [comment]
Yes I understand that. What I'm saying is as far as I can tell I have all the required open graph data in place. Open graph works everywhere else outside of sms messages. I don't know why it's not working but this is a common issue that people have.

For all I know Android/iPhones are doing something else behind the scenes when they see common links like YouTube with sms.

Long story short, I don't know how to fix it on sms and the only potential solution I found didn't work. Many people are having this issue. 

It's open source, so you or anyone are welcome to try and fix it.

**Comment by ShaneIsrael** [comment]
Yes I understand that. What I'm saying is as far as I can tell I have all
the required open graph data in place. Open graph works everywhere else
outside of sms messages. I don't know why it's not working but this is a
common issue that people have.

For all I know Android/iPhones are doing something else behind the scenes
when they see common links like YouTube with sms.

Long story short, I don't know how to fix it on sms and the only potential
solution I found didn't work. Many people are having this issue.

It's open source, so you or anyone are welcome to try and fix it.
