### ISSUE TITLE
Feature Request: Custom Thumbnails 

### ISSUE THREAD

**Issue by truthsword** [ShaneIsrael/fireshare#122]
I need to change certain thumbnails... Particularly the all black ones. Presently I do that manually, though it is complicated to figure out the relationship between the video file name and the appropriate folder that holds the thumbnail. Thanks for your consideration.

**Comment by ShaneIsrael** [comment]
I have added this to the feature suggestions section our our wiki here: https://github.com/ShaneIsrael/fireshare/wiki
