### ISSUE TITLE
[Feature Request] Auto scan library after upload

### ISSUE THREAD

**Issue by Synt3x** [ShaneIsrael/fireshare#125]
It would be great if Fireshare automatically scanned the library after a successful upload.
So we don't have to press the scan library button or wait for the automatically scan to execute.

**Comment by ShaneIsrael** [comment]
This is available in the develop image. 

When an upload finishes, fireshare will attempt to start a scan. If a scan happens to already be running, nothing will happen and your video may not show up until the next scan.
