### ISSUE TITLE
[Bug] Webview is to small

### ISSUE THREAD

**Issue by Synt3x** [ShaneIsrael/fireshare#126]
**Describe the bug**
When I visit my Fireshare instance I get horizontal scrolling.

**To Reproduce**
I just visit any Fireshare webpage  on my phone and I get the horizontal scrolling.

**Expected behavior**
I expect that the full with of the website should be visible. (no scrolling sideway).

**Screenshots**
![image](https://user-images.githubusercontent.com/11620295/183454423-e9a17521-be13-495e-befd-647584d0e2c4.jpeg)

**Additional context**
- iOS
- iPhone 13 Pro
- Safari and Firefox
- Fireshare v1.2.3

Doesn't happens on my partners phone (iphone 11).

**Comment by ShaneIsrael** [comment]
Open the sidebar, change the size of the cards to be smaller.

**Comment by Synt3x** [comment]
Like this? Doesnt seem to work.
https://user-images.githubusercontent.com/11620295/183466636-3286465f-f21a-4d00-a5a3-90dcfab5bacd.MOV

**Comment by Shane-stage** [comment]
You need to tap on the hamburger icon on the top left, and when the sidebar opens drag the slider to the left to make the cards smaller.

**Comment by ShaneIsrael** [comment]
You need to tap on the hamburger icon on the top left, and when the sidebar
opens drag the slider to the left to make the cards smaller.

**Comment by Synt3x** [comment]
Okej, that solved the problem. But shouldnt the slider still resize the content inside of the width of the screen? If it's need to be minimum the, its better to hide the slider?

If I'm watching a shares link, then the slider isnt showing and content is outside if the width.

![image1](https://user-images.githubusercontent.com/11620295/183480441-fb3070dd-951a-4009-b8c4-2fc48aff87b3.png)

![image2](https://user-images.githubusercontent.com/11620295/183480468-8f8fcc33-6af7-4ac2-bbe4-01e97a409d2a.png)

**Comment by ShaneIsrael** [comment]
The slider is only for changing the size of the cards. It doesn't change
the size of anything else.

Fireshare is first and foremost a desktop experience. While I have tried to
make it fairly mobile friendly, it's not perfect and even more so on
smaller screen devices.

**Comment by Synt3x** [comment]
No worries, I'm glad that you created this project. Just trying to help out and report the issues I find, to make the experience better.

I haven't done any development in NodeJS and only written few small python scripts.

**Comment by Synt3x** [comment]
I looked into this a bit more and found it that the video view is rescaling depending on the view. But the menu below the video is not rescaling so the with is 2 big. 
![image](https://user-images.githubusercontent.com/11620295/183628168-f27df905-e60f-4ceb-9435-09e19787a16b.png)


Maybe some text in the title should be hidden when view is to small.

**Comment by ShaneIsrael** [comment]
It does rescale but to a point. When you get that small it can't rescale
any further so there isn't anything I can do unless I make it completely
change the layout for smaller screens which is not something I'm interested
in doing since I rarely use it on mobile.
