### ISSUE TITLE
Fireshare docker stop working when I reboot

### ISSUE THREAD

**Issue by kevinhu121** [ShaneIsrael/fireshare#130]
Fireshare works properly when I first run it, but when I reboot my computer the application gave errors and I'm unable to access my videos.

This is the command I used to deploy fireshare, almost as same as the one provided in this github but added restart=unless-stopped
`docker run --restart=unless-stopped --name fireshare -v $(pwd)/fireshare:/data:rw -v $(pwd)/fireshare_processed:/processed:rw -v /media/karis/backup/DESKTOP-IIJBPB0/Current\ Video/Valorant:/videos:rw -p 8080:80 -e ADMIN_PASSWORD=my-admin-password -d shaneisrael/fireshare:latest`

It deployed fine and I can access fireshare at ip-address:8080, I logged in and scanned my videos, everything was fine.

However when I reboot the computer, fireshare no longer works. I can still go to ip-addr:8080 but I got an error `<html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`, then I clicked login and enter my info. It gave me this error.
![image](https://user-images.githubusercontent.com/24880171/185806772-c3525573-9bac-418d-8a56-0e327d941c10.png)
After a minute, the site can't be reached, ip-address refused to connect. 

Here's the log I got about this issue using `docker logs fireshare` 
[fireshare error.txt](https://github.com/ShaneIsrael/fireshare/files/9389794/fireshare.error.txt)

I ran docker on Linux Mint 21 on a Lenovo Desktop, Docker version 20.10.17, build 100c701. I ran the docker run command in my home directory and my game clips are stored on external hard drive mounted at /media/karis/backup. I ran various other containers and all these container work properly after I reboot my computer.

I'm new to using Linux but let me know what other information you need from me to resolve my issue.

**Comment by ShaneIsrael** [comment]
After restarting run the docker command again to bring the app back up. If for some reason that error is still happening, delete the docker image and pull a fresh image down. You can always try with this command `--pull=always` added to your docker run command. 

It looks like you stopped the image while the internal python scheduler was doing something and so it didn't properly stop. Pulling a new image won't erase any of your settings/data since those are saved in the volume maps.

**Comment by ShaneIsrael** [comment]
I pushed up a potential fix for this, for now you can find it in the `shaneisrael/fireshare:develop` image. I don't have time to test it right now but I believe it will solve this problem from happening.

**Comment by kevinhu121** [comment]
After restarting I was able to restore the functionality of fireshare container by force removing it and redeploying with the docker run, but I have to do it for every reboot. I tried deleting the image and pulling a new one, that did not survive after the reboot. However, the develop image did not have the issue with rebooting, so I'll close this issue.
