### ISSUE TITLE
[Feature Request] Autoscan as Admin

### ISSUE THREAD

**Issue by Netri0** [ShaneIsrael/fireshare#133]
From what I can tell, the auto scan only works if you're not logged in. I think it's best if auto scan worked regardless of being logged in or not. By being logged in, I have the privilege of deleting videos and editing titles, but no auto scan; vice versa.

Btw great job so far!

**Comment by ShaneIsrael** [comment]
Autoscan works regardless of whether you are logged in or not. By default it runs every 5 minutes unless you change that.

**Comment by Netri0** [comment]
My bad. I meant when you upload a file, and then it automatically scans the library. It doesn't

**Comment by ShaneIsrael** [comment]
Scan on upload was recently added. It's currently only available in the develop image though.

**Comment by Netri0** [comment]
My bad. I meant that when I'm logged in and I upload a file then and there, it won't automatically scan the library. I am on the develop image btw

**Comment by ShaneIsrael** [comment]
Check that there isn't a fireshare-scan.lock file in your data folder. If there is, restart the container and try again. Also, do a pull on the Develop image, you might be on an old develop image that doesn't have the feature.

**Comment by Netri0** [comment]
I only see the config and db in the data folder. I'm currently on the latest develop image. I made a video showing how it looks on my screen: https://youtu.be/TAmliX2IGps

**Comment by ShaneIsrael** [comment]
So based off your video, you're uploading too quick. When you upload a video, it kicks off the scan. The scan at least 30 seconds, maybe longer if you have a lot of videos. So if you log in, upload a video and wait a minute before you upload the next one you should see it show up. 

Or just upload as fast as you can and eventually they will all be scanned in.

Basically, you are trying to upload the 2nd video while the scan from the first video is still running. Then when you log out and try it, the scan has finished so it "seems" like its a login problem, when really its just that you are trying to upload a video before the last scan finished. Which is fine, that isn't a problem. That video will just have to wait until the next scan happens.

**Comment by ShaneIsrael** [comment]
Actually, you weren't wrong. I forgot to push up the code change for kicking off the scan on admin upload... a new develop image is building, once thats built pull it and issue should be resolved.

**Comment by Netri0** [comment]
Glad it's been resolved!
