### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Kornster** [ShaneIsrael/fireshare#134]
I just discovered this container in Unraid and this is right up my alley (Thumbs up to then creators) to self host my own game clips to share around with friends. Can  i request a screenshot feature be implemented so i can upload my game screenshot archives

**Comment by ShaneIsrael** [comment]
This is not something that is in my immediate goals for Fireshare but is something that may eventually be implemented. There's no timeline on it, there's a lot of other features and improvements I want to do first before I get to screenshot sharing. 

However, it is open source and I will welcome anyone who wants to add the feature to Fireshare so long as the implementation is done well.
