### ISSUE TITLE
[Feature Request] Delete videos(s)

### ISSUE THREAD

**Issue by Dulanic** [ShaneIsrael/fireshare#136]
Hello, I'd like to see the ability to delete videos from the webui. This should also delete the videos from the filesystem. This is obviously easily done via cli, but this would be a time saver for sure. 

BTW, love the program!

**Comment by Dulanic** [comment]
Im an idiot, I see you can!

**Comment by fizzyfrys** [comment]
I don't know if this will re open the issue, 

But for anyone searching for how to delete videos:
Go to "My Videos" tab, then click on the pencil to edit whichever video you want to delete. Then there you'll find the delete button.
