### ISSUE TITLE
Grey screen, play button disabled and wont play videos.

### ISSUE THREAD

**Issue by quiquos** [ShaneIsrael/fireshare#140]
On Edge  (I currently only have this browser), when I press a video to play it just shows a gray screen and the buttons bar.
The play button and the 3 dots button are disabled, and it won't play the video.

![image](https://user-images.githubusercontent.com/37425944/191616459-3dcef8a6-49b7-46dc-be02-d34a4a8c9793.png)
It's an mp4 file.
I tried with some other videos, but nothing.
On Ipad safari works.
On another laptop, chrome, it just plays the audio, and no image is shown.

This is running on docker (proxmox lxc container OS turnkey - debian 10)

Docker compose
version: '3.3'
services:
  fireshare:
    container_name: fireshare
    image: shaneisrael/fireshare:latest
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - /srv/fireshare/fireshare_data:/data #change this to your folder location
      - /srv/fireshare/fireshare_processed:/processed #change this to your folder location
      - /srv/fireshare/fireshare_videos:/videos #change this to your folder location
    environment:
      - ADMIN_USERNAME=admin #please change this
      - ADMIN_PASSWORD=admin #please change this
      - SECRET_KEY=somestr1ng!
      - MINUTES_BETWEEN_VIDEO_SCANS=1  #how often should the system scan?
      - PUID=1000 #change this to match your server settings
      - PGID=1000 #change this to match your server settings

https://test.quiquos.space/      <- Site to test

**Comment by ShaneIsrael** [comment]
Get access denied trying to go to the test site. Is your mp4 encoded in h264? If its encoded in h265 it will not play since html5 video players do not support h265 playback.

**Comment by ShaneIsrael** [comment]
https://caniuse.com/hevc

This is probably why it works on your ipad. Most browsers do not support that encoding. So my guess is that its encoded in h265. You'll need to re-encode to h264 or change your recording software to encode using h264.

**Comment by quiquos** [comment]
Hi @ShaneIsrael,
thanks for the answer.
After a quick test, that was the issue.
