### ISSUE TITLE
NVIDIA GPU Support

### ISSUE THREAD

**Issue by Uruknara** [ShaneIsrael/fireshare#145]
Hello, i was wondering if you could add gpu support so player could be a lot faster and easier so they not eating the cpu like cookie please ?

**Comment by ShaneIsrael** [comment]
GPU Support is something I want to add eventually but it will take a ton of work and understanding to properly have that in place. This is not likely to happen anytime soon unless somebody with experience doing GPU video transcoding and serving on the fly is able to help. 

Sorry if this isn't the answer you were looking for.

**Comment by Uruknara** [comment]
Yes I think it would be very very difficult to make but so cool to add
