### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Zottelchen** [ShaneIsrael/fireshare#151]
**Describe the bug**
After running for a while, Fireshare took a huge amount of memory (~3GB), leading to an unstable system.

**To Reproduce**
Unknown

**Expected behavior**
Don't do that.

**Additional context**
`ps -ef` showed a huge amount of  `/usr/local/bin/python /usr/local/bin/fireshare bulk-import` & `/bin/sh -c fireshare bulk-import`. Docker was unable to stop or kill the container or even read the logs. The videos are on a mounted sshfs.

**Comment by ShaneIsrael** [comment]
How many videos do you have in your video folder and how large are they? My first thought is that the memory is climbing on your initial import scan. I don't believe this is a memory leak, but rather you may have so many videos that its trying to import initially that its taking 3GB of memory to build the database. After that initial import, it shouldn't be an issue. 

A work around you could try if you do have a ton of videos is to temporarily move half the videos, run fireshare and let it import the first half. Once its done, turn fireshare off and move the other half of the videos back. Turn fireshare on and let it import that half.

**Comment by Zottelchen** [comment]
Currently I have 20 Videos, 1,8 GB. The last video was added on 16.10. As far as I could tell tne import also finished on the 16th, at least I was able to share the video back then.

**Comment by ShaneIsrael** [comment]
20 videos should not be enough to cause a problem, and if the total size is only 1.8GB for all 20 videos that is definitely not the issue. 

I have never seen this issue myself and I have 612 videos at a total size of 236 GB. I've never seen anyone else report this either so I'm not sure if there is anything I can do other than keep an eye out for more reports. Code wise, nothing stands out to me that would cause a memory leak on the bulk import. At most, it might use a lot of memory initially for a large import of thousands of videos.
