### ISSUE TITLE
Site not properly loading videos on mobile

### ISSUE THREAD

**Issue by UJGA** [ShaneIsrael/fireshare#156]
**Describe the bug**
Opening the website on mobile (iOS) the page loads fine and displays all clips. Usually one video will successfully play, however once it has been minimized and second video is selected the clip will pop up for a fraction of a second then will not open another clip. Sometimes refreshing the page fixes this, sometimes it does not. i have experienced this on both Chrome and Safari.  I have been able to replicate this on 2 devices so far.

Seems likely that the issue is a compatibility issue with how iOS handles playing web videos.

**To Reproduce**
1. Load the page
2. Play a clip
3. Close first clip
4. Attempt to play a second clip

**Expected behavior**
Clips after the first will open and play

**Screenshots**
Here is a video of the issue:
https://youtube.com/shorts/Gu_Tr8w7ipg?feature=share

**Desktop (please complete the following information):**
 - iPhone 14 Pro, iOS 16.0.2, Safari and Chrome
 - iPad Pro, iPadOS 16, Safari and Chrome

**Comment by Shane-stage** [comment]
On Android, using both Firefox and Chrome I cannot seem to replicate the issue you are seeing, opening > playing > and closing multiple videos works (via the modal preview) without problem. 

Trying this on my iPad which is the closest I have to an iPhone does seem to have the same issue you describe. I don't often develop for iOS so I'm not familiar with what might be causing this problem and why it only happens on iOS or even where I would begin debugging. 

Will keep this open in case anyone has an idea on what might be causing it or what can be done to fix it.

**Comment by ShaneIsrael** [comment]
On Android, using both Firefox and Chrome I cannot seem to replicate the issue you are seeing, opening > playing > and closing multiple videos works (via the modal preview) without problem. 

Trying this on my iPad which is the closest I have to an iPhone does seem to have the same issue you describe. I don't often develop for iOS so I'm not familiar with what might be causing this problem and why it only happens on iOS or even where I would begin debugging. 

Will keep this open in case anyone has an idea on what might be causing it or what can be done to fix it.

**Comment by ShaneIsrael** [comment]
Resolved in the latest release.
