### ISSUE TITLE
Clicking play in viewing mode closes the menu

### ISSUE THREAD

**Issue by dawson-vilamaa** [ShaneIsrael/fireshare#159]
**Describe the bug**
When I try to play a video in fullscreen by clicking the video player, the menu closes, but the video/audio still plays in the background. The menu slides down in the same way it would if you clicked the X button in the top right.

**To Reproduce**
1. Go to My Videos
2. Select a clip
3. Click anywhere on the video player element (not the actual play button)

**Expected behavior**
The video plays while in the viewing menu.

**Desktop:**
 - Browser: Brave, Edge

**Additional context**
This bug does not happen in Firefox, I'm guessing it's because it uses a different video player. This bug does not happen if I click the actual play button in the bottom left of the video element.

**Comment by ShaneIsrael** [comment]
Interesting, thanks for the report. I'll try to look into this over the weekend.

**Comment by ShaneIsrael** [comment]
@dawson-vilamaa This should now be fixed in latest build (version 1.2.7). It will take about 20 minutes for the build to be live.
