### ISSUE TITLE
How to remove video?

### ISSUE THREAD

**Issue by jforstneric** [ShaneIsrael/fireshare#164]
First off, really like Fireshare!

I'm wondering how to properly remove a video? I can delete it from ~/fireshare/dev_root/fireshare_videos/ but the web UI then just shows that the file is missing. I'm guessing I could also manually go into the sqlite DB at fileshare_data but that seems a bit hackish.

**Comment by Shane-stage** [comment]
Have you tried using the delete button within fireshare when editing a video? This will permanently delete the video file.
If you manually delete videos, fireshare will give a "missing file" warning which you obviously don't want. 

If however you want to save the video, but have it removed from fireshare, move the video file manually somewhere else outside of the fireshare media directory, then go into the fireshare ui and delete the video to remove the entry from its database.

**Comment by ShaneIsrael** [comment]
Have you tried using the delete button within fireshare when editing a video? This will permanently delete the video file.
If you manually delete videos, fireshare will give a "missing file" warning which you obviously don't want.

If however you want to save the video, but have it removed from fireshare, move the video file manually somewhere else outside of the fireshare media directory, then go into the fireshare ui and delete the video to remove the entry from its database.

**Comment by jforstneric** [comment]
I'm sorry, I'm an idiot, completely missed that :-(

Again, thanks for Fireshare, it's exactly what I was looking for as a way to easily share family videos.

**Comment by Shane-stage** [comment]
No worries!

**Comment by ShaneIsrael** [comment]
No worries!
