### ISSUE TITLE
Feature request: Intergration with ShareX to instant upload screenshots

### ISSUE THREAD

**Issue by maaknaamaan** [ShaneIsrael/fireshare#165]
Hi,

First off, thanks for this awesome project! I would like to suggest an option to be able to instantly upload to the server/site by using ShareX. This would make it so much faster and even more easy to share any screenshot or screen video recording that you do.

ShareX is free on their site and on Steam and is able to upload to many websites, but that gives my data/screenshot out of hands :)
Here is an example of their custom uploader section.

https://i.imgur.com/RM6iNhU.png

Thanks for reading!

**Comment by Shane-stage** [comment]
Hi, this is definitely a neat idea at least for video. Probably not something I will be prioritizing but I'll note it down in the Wiki as potential future features to work on.

**Comment by ShaneIsrael** [comment]
Hi, this is definitely a neat idea at least for video. Probably not something I will be prioritizing but I'll note it down in the Wiki as potential future features to work on.
