### ISSUE TITLE
Feature request: Multi-Select/Select All Additional Features

### ISSUE THREAD

**Issue by ReactionShot** [ShaneIsrael/fireshare#168]
Hi @ShaneIsrael, 

I love the tool!  I am trying to organize my video files within the uploads folder and I realized that the uploads folder is recursive so you can create a folder structure within uploads and put clips into different game folders for instance.

I saw that you have a feature request in the Wiki for "Multi-Select / Select All for public/private visibility", but I would like to extend this feature request and see if it's possible to also use the multi-select for selecting new file locations (e.g. I moved a clip from "/uploads/" to "/uploads/Call of Duty/") and I want to change the pointer to the new file location.  Alternatively/Additionally, if that's not possible then I'd like to use the Multi-Select/Select All for deletion.  If I can't change the file location then I'd like to use the multi-select feature to delete selected files.  I spent about 5 minutes manually selecting each clip and deleting them, but I guess an alternative for now is just removing the container and pulling it back down.

I'm in the initial stages of deploying fireshare, but I think that moving (finding the file's new location) would be preferable to deleting and recreating, especially if the link has already been shared on multiple platforms.

Thanks!

**Comment by ShaneIsrael** [comment]
Being able to multi-select and change the file locations is something I have wanted to do I just haven't gotten around to actually doing it. So it's definitely on my to-do list I just need to find the time to sit down and actually pump out the feature. 

So it's definitely something I want to do but I don't have a time-frame for when I will get around to actually doing it unfortunately.

**Comment by ReactionShot** [comment]
I attempted to follow the Local Development [steps](https://github.com/ShaneIsrael/fireshare#local-development) to work on this feature, but for some reason I cannot login as admin so I cannot upload a clip.

![image](https://user-images.githubusercontent.com/5529362/212835886-9a9b0caf-d754-4547-b1a3-a3fe3ce6217a.png)

**Comment by ShaneIsrael** [comment]
What errors do you seen in the console from the backend?

**Comment by ShaneIsrael** [comment]
No response
