### ISSUE TITLE
Videos not playing on the site in any browser

### ISSUE THREAD

**Issue by Myndmelt** [ShaneIsrael/fireshare#169]
**Describe the bug**
I have fireshare all set up via Docker on a TruenasScale server. v22.12.0
I am able to upload a file however not able to play them, at all.
In my example it is a 19 second mp4 at 93MB.
I have also uploaded a 35 second 46MB MP4 and getting the same results.
When I go to play the file it opens the player, I will see a circle in the middle for a couple seconds and then nothing. I cant click play or anything on the player itself. I have tried Opera Gx, Edge, Chrome and Firefox and all produce the same results. I can confirm the video is successfully uploaded to the videos/uploads folder. and the file will play from the directly if I access it with my PC.

**To Reproduce**
Login to fireshare
Upload a video.
Wait a few moments for the next scan to finish.
Try to access video and the video does not play.

**Expected behavior**
The video would play as expected.

**Screenshots**
<img width="855" alt="opera_52Mc4fmxxx" src="https://user-images.githubusercontent.com/80299469/213379956-2059efa6-ca6d-4ccc-9c2d-4b1fa79ca994.png">

**Desktop (please complete the following information):**
 - Firefox, Chrome, Edge, Opera

**Additional context**
I just set up the server so I have not previously been able to play the files.

**Comment by ShaneIsrael** [comment]
I am not familiar with Truenas but make sure that you have properly set up your PUID and PGID in the fireshare docker environment variables to match your Truenas **user** and **group** ids. This needs to be a user/group that has read/write access to the files and folders that you specified in the docker setup. 

Also make sure that the .mp4 videos you are uploading or testing with are NOT encoded in h265 or any other standard that is not h264. 

h264 will work fine. h265 is very hit or miss on whether it will work and often depends on the browser being used.
