### ISSUE TITLE
share link w/ timestamp in admin ui does not work

### ISSUE THREAD

**Issue by iwa** [ShaneIsrael/fireshare#175]
**Describe the bug**
When you watch a clip from the "My Videos" panel, when logged in as admin account, and try to click on the share w/ timestamp button, it tells you it did copy but it didn't

**To Reproduce**
1. Log in as admin
2. Go to My videos
3. Watch a clip
4. Click on the Clock button
5. Nothing is copied

**Expected behavior**
Link should be copied

**Desktop (please complete the following information):**
 - Browser: Version 111.0.5563.50 beta (64 bits)

**Comment by ShaneIsrael** [comment]
I just followed your steps and I can't reproduce. Tested in Firefox and Chromium (edge, chrome, etc). You are using a beta of some browser, could be an issue with that browser being in beta or maybe you have an extension or browser setting that isn't allowing modification to your clipboard.

**Comment by ShaneIsrael** [comment]
Closing due to no response and I'm unable to reproduce the described issue.
