### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by jenny787** [ShaneIsrael/fireshare#176]
**Describe the bug**
installed docker version on windows and also tried ubuntu.  it installs fine, everything seems to be working.  But i can't login.  If i try logging i get a red error on the bottom.

**To Reproduce**
just install default docker compose setup, and try to login.

**Expected behavior**
expect to be able to log in.

**Screenshots**

**Desktop (please complete the following information):**
desktop windows, desktop ubuntu.

**Additional context**

**Comment by ShaneIsrael** [comment]
Can you send me your docker compose file? Or if you are not using the docker compose file the complete docker run command you are using?

**Comment by jenny787** [comment]
Sorry for the delay, here is the compose file I used.  All i changed was 
the password.



------ Original Message ------
From "Shane Israel" ***@***.***>
To "ShaneIsrael/fireshare" ***@***.***>
Cc "GitRinger" ***@***.***>; "Author" 
***@***.***>
Date 3/11/2023 10:55:23 AM
Subject Re: [ShaneIsrael/fireshare] unable to login (Issue #176)

**Comment by jenny787** [comment]
I just found out what was doing it.  Once the container is up and 
running, using localhost to log in gives an error.  If I put the full ip 
address of the docker host, it works fine.


------ Original Message ------
From "Shane Israel" ***@***.***>
To "ShaneIsrael/fireshare" ***@***.***>
Cc "GitRinger" ***@***.***>; "Author" 
***@***.***>
Date 3/11/2023 10:55:23 AM
Subject Re: [ShaneIsrael/fireshare] unable to login (Issue #176)
