### ISSUE TITLE
Discord Embeds not working

### ISSUE THREAD

**Issue by ayayrom** [ShaneIsrael/fireshare#179]
**Describe the bug**
While the discord client understands it is a video, clicking on it doesn't allow the video to play.

**To Reproduce**
1. Upload video to Fireshare
2. Grab video link
3. Post link on discord
4. Click play

**Expected behavior**
Video playing as intended

**Screenshots**
![image](https://user-images.githubusercontent.com/61670781/229658679-8eeded11-f9e0-4c02-a59a-6cd23dc8f34f.png)

**Desktop (please complete the following information):**
 PC, mobile

**Additional context**

**Comment by ShaneIsrael** [comment]
This is a discord playback issue for embeds. As far as I can tell the video embeds work fine on other sites but I can't fix discords embedded playback.
