### ISSUE TITLE
[Question] Search LDAP without memberOf enabled

### ISSUE THREAD

**Issue by Cruv** [ShaneIsrael/fireshare#181]
OpenLDAP comes without memberOf being enabled by default as an overlay. Is there a way to use the LDAP authentication without utilizing the memberOf attribute?

**Comment by ShaneIsrael** [comment]
That's a good question and honestly I do not know. Somebody else added the LDAP support which I approved however I personally have no experience with LDAP authentication.

**Comment by ShaneIsrael** [comment]
@d-513 is this something you can comment on?

**Comment by d-513** [comment]
At least with the current implementation, no. It requires memberOf enabled.

**Comment by Cruv** [comment]
I might try to fork and see what I can do. Thank you!On Apr 15, 2023, at 9:45 AM, d513 ***@***.***> wrote:﻿
At least with the current implementation, no. It requires memberOf enabled.
