### ISSUE TITLE
Can someone write some kind of example on how to setup a reverse proxy for this thing?

### ISSUE THREAD

**Issue by stautonico** [ShaneIsrael/fireshare#185]
As the title states, there are so many little issues with getting this thing working correctly behind a reverse proxy, can we have some kind of docs with an example of how to use this behind a reverse proxy? Otherwise, it takes hours of digging through issues and testing stuff.

**Comment by ShaneIsrael** [comment]
What do you mean "So many little issues?" it's fairly straight forward and should be no different than getting anything else working behind a reverse proxy. 

What specifically are you having a problem with?

I wrote a guide here on how to set this up on a simple ubuntu/linux system. If all you need is help setting up a reverse proxy the end of the guide explains how to do it with Nginx Proxy Manager. 

https://shitshanesays.com/complete-guide-self-host-fireshare-behind-a-subdomain/
