### ISSUE TITLE
Upload card not shown on first time load

### ISSUE THREAD

**Issue by kevoh1516** [ShaneIsrael/fireshare#189]
**Describe the bug**
When a user visits Fireshare for the first time, the upload card is not visible and they have to refresh the page to see it.

**To Reproduce**
1. Open an incognito window
2. Go to https://v.fireshare.net/
3. Upload card is not visible
4. Refresh the page
5. Upload card is visible

**Expected behavior**
The upload card should be visible on first time load.

**Comment by Shane-stage** [comment]
Thanks for pointing this out.
