### ISSUE TITLE
Support photos and audio

### ISSUE THREAD

**Issue by Encode42** [ShaneIsrael/fireshare#198]
Fireshare works so great that I want to share even more content through it! Most notably, photos and audio.

Currently, I have Fireshare set up on top of a Pydio mount, to upload videos through it. (due to #187 - no rush) While Pydio already supports sharing audio, photos, *and* video, the implementation isn't great, as is often janky. As such, letting Fireshare handle all of the above would simply be great!

**Comment by ShaneIsrael** [comment]
This is a neat idea but something that I am unlikely to develop into Fireshare. Fireshare is meant to solve one specific problem which is simple media sharing with minimal complexity. There are other applications that are much better suited for hosting photographs and audio files.
