### ISSUE TITLE
MINUTES_BETWEEN_VIDEO_SCANS max value ?

### ISSUE THREAD

**Issue by EctoBoggan** [ShaneIsrael/fireshare#210]
Hey,

I just wanted to know what's the max possible value of MINUTES_BETWEEN_VIDEO_SCANS ?

Because I don't need it to scan every 5 minutes so I putted 1440 (24h) and it doesn't seem to work (5 mins works tho)...

Have a nice day.

**Comment by ShaneIsrael** [comment]
There isn't a max, 1440 should work just fine. However that interval will restart anytime the application itself restarts so it could be that your system is restarting the fireshare container before the 1440 interval is reached? 

The scan takes very little system resources and depending on how many videos you are trying to scan is super quick thus why its set to 5 minutes by default.

**Comment by EctoBoggan** [comment]
Okay I get it,
I stop and restart my containers every day in order to backup them. so it will never reach 24h.
I'll put a smaller value.

Thanks a lot !
