### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by 45triX** [ShaneIsrael/fireshare#212]
I am trying to upload a 1:15s clip that is 561MB in size and it gets to ~30% upload and it just stops and I get a red error message at the bottom of the screen saying `an error occurred while uploading your video.` (the file in question is 1080p using h.264 encoding)

**To Reproduce**
1. Go to my fireshare instance
2. log in as admin
3. click the upload button
4. click the video file to upload
5. wait till it hits 30%

**Expected behavior**
Should be able to upload file

**Screenshots**
[Fireshare-Error](https://github.com/ShaneIsrael/fireshare/assets/142095995/ed82515c-24c0-497a-be41-ac6ab0c85a78)

**Desktop (please complete the following information):**
 - Tried in Firefox and Brave browsers

**Additional context**
No additional context AFAIK

**Comment by Shane-stage** [comment]
This is not a bug, this has to do with your reverse proxy setup. If you don't have your reverse proxy properly setup for uploads it's going to pre-maturely kill your upload connection. 

Please look at the Frequently Asked Questions part of the README which will give you an example of how to handle this with nginx.

**Comment by 45triX** [comment]
> This is not a bug, this has to do with your reverse proxy setup. If you don't have your reverse proxy properly setup for uploads it's going to pre-maturely kill your upload connection.
> 
> Please look at the Frequently Asked Questions part of the README which will give you an example of how to handle this with nginx.

Ah ok I was also wondering if additional user accounts could be created I don't seem to see anywhere that mentions this
