### ISSUE TITLE
Feature Request: per user video access

### ISSUE THREAD

**Issue by claytondukes** [ShaneIsrael/fireshare#218]
First, thanks for making this! nice work :)
Is there any chance you'd be able to add a user auth capability and only allow viewing a video by user or group?
I'd even be willing to pay you a bit for the work if you are interested.

**Comment by RisedSky** [comment]
Can be aggragated with #215

**Comment by ShaneIsrael** [comment]
@claytondukes Please see my comment on #215 here. https://github.com/ShaneIsrael/fireshare/issues/215#issuecomment-1766538245
