### ISSUE TITLE
Question about LDAP and Fireshare

### ISSUE THREAD

**Issue by DamienDrsss** [ShaneIsrael/fireshare#223]
Hi,

I want to be able to connect to Fireshare with a domain user but i'm stuck.
My docker compose looks like that:
![image](https://github.com/ShaneIsrael/fireshare/assets/149476715/0775317c-5a0b-47dc-8aed-dc8f6fe0c25b)

It doesn't work, can you help me pls ?

Regards,

**Comment by ShaneIsrael** [comment]
So I have close to 0 experience with LDAP and was not the person who implemented it within Fireshare so I apologize in advance that I'm probably not going to be much help. 

However, looking at your docker compose file I'm wondering if maybe you messed up the "LDAP_USER_FILTER" section. You seem to have left `{input}` in place for `uid` and `mail`. I'm pretty sure you need to replace those with a uid or mail that you want to filter by, which you are not doing and is probably why the LDAP isn't working. 

![image](https://github.com/ShaneIsrael/fireshare/assets/1677199/e1535688-6590-4879-84b3-167a93c98fa7)

So you need to change `{input}` on both the uid and mail section to be the username that you use to login to the fireshare web ui according to the docs.

So in your login username was "DamienDrsss" it should probably look like this
`(&(|(uid=DamienDrsss)(mail=DamienDrsss))(objectClass=person))`

**Comment by DamienDrsss** [comment]
Hi,

Thanks for your answer.
But I see my container dosn't work as soon as put the "LDAP_ENABLE" variable:

![image](https://github.com/ShaneIsrael/fireshare/assets/149476715/1b386fff-d53f-4e92-aaa5-bdaa4ec0605c)

Do you have an idea pls ?

**Comment by ShaneIsrael** [comment]
@DamienDrsss Did you completely ignore my suggestion that you have an invalid value for one of the other LDAP environment variables. If that value is invalid, the container could be error'ing and failing to start. Do you have container logs?

**Comment by DamienDrsss** [comment]
Hi @ShaneIsrael , 

No, I used your advice but same problem...
The log when I launch the container:

![image](https://github.com/ShaneIsrael/fireshare/assets/149476715/6a190e22-5fd3-45c0-8961-be42ad27a54f)

Thanks for the help 

Regards

**Comment by BulletMemes** [comment]
@DamienDrsss Just based off your first screenshot, you're forgetting to set your [LDAP URL](https://github.com/ShaneIsrael/fireshare/blob/main/LDAP.md#ldap_url), could you confirm you actually have that set?
