### ISSUE TITLE
Login without LDAP

### ISSUE THREAD

**Issue by CrypticMetaphor** [ShaneIsrael/fireshare#228]
Having the ability to enable signups, or admin can create usernames with temporary passwords that request for a change upon login would be superb. 

Unfortunately there isn't clear guidance on how to utilise LDAP with Fireshare for novice user like myself, so having the ability to hold usernames and passwords locally would be super.

**Comment by ShaneIsrael** [comment]
You do not need LDAP to login if you do not have it. Fireshare is designed specifically to not have a user system outside of the admin account to keep things simple. Adding a user system means having to support a much broader feature set and design in a whole permission system around that. 

If a user system is something you need or want, Fireshare is not the solution for you and you might be better off with something like Peertube which has a robust user system and is designed for user interaction. 

Fireshare is meant to be as simple and easy to setup as possible with the sole purpose of quickly and easily sharing clips.

**Comment by p0358** [comment]
It's not really a complicated use-case I think, to have some simple way of allowing friends to upload, but not allow public uploading without any authentication (but also not have everyone sit on the admin account...). I think some kind of fallback for non-admin user list akin to something like .htaccess file (with just a list of users and hashed passwords) could be reasonable. (and setting up whole LDAP just for this alone would be a huge overkill)
