### ISSUE TITLE
[Suggestion]: Per folder file scanning

### ISSUE THREAD

**Issue by rolandogdp** [ShaneIsrael/fireshare#231]
First, great software, thank you for making this accessible.

I want to suggest that for large libraries, with over 1.5 To of recordings, a full scan can take several minutes and can even sometimes be counted in hours.
 It would be nice to be able to restrict which files/folders are scanned and not rescan the whole videos folders. 
Or to be able to use the UI to upload a file which would be instantly added to the DB instead of waiting for a WHOLE rescan..

**Comment by ShaneIsrael** [comment]
This is not a bad idea in the slightest. I'll give this some thought. I definitely think just scanning the uploads folder is a good idea after an upload is complete. 

I might be able to have a "manual folder scan" option in the UI where you can select your top level folder that you want to scan and have it start one for just that folder. Let me think about this for a bit.

**Comment by ShaneIsrael** [comment]
@rolandogdp I have improved uploading such that uploaded files are immediately scanned in. This will be available on the next production release (which should be tonight so long as my testing passes). 

https://github.com/ShaneIsrael/fireshare/pull/233
