### ISSUE TITLE
[Suggestion] avoid making the first frame of a video the thumbnail

### ISSUE THREAD

**Issue by eliasbenb** [ShaneIsrael/fireshare#235]
Currently, the thumbnail for uploaded videos is the first frame of the video. For me, the first frame is usually a blank screen.
In many cases the first and last frames of a video don't have anything to do with its content.

There are many different options you could go with to select the thumbnail frame, but the simplest would be choosing the frame at the middle of the video or just choosing a random frame.

**Comment by ShaneIsrael** [comment]
This should be an easy update and I agree the first frame is not likely the best choice in many scenarios. I may create an environment variable where you can specify at what location in your videos (0 to 100) where 50 would be in the middle to create the thumbnail from.

**Comment by ShaneIsrael** [comment]
Added in PR #237, will be available sometime today in build v1.2.17

You'll need to add a new environment variable `THUMBNAIL_VIDEO_LOCATION` to your docker compose file / command. See the wiki here for what the expected value should be. https://github.com/ShaneIsrael/fireshare/wiki/Fireshare-Configurables
