### ISSUE TITLE
https:// being omitted from the generated link

### ISSUE THREAD

**Issue by turnercore** [ShaneIsrael/fireshare#250]
This may not be an issue if you're using a normal domain, but I'm using a .dev domain.

The links the app generates are `my.domain.dev/videolinkurlhashstuff`, which is probably expected behavior. But a lot of things won't recognize urls with lesser used tlds as links unless you put the http:// or https:// in front of the link.

It would be awesome if there was a setting to enable the copied link to include the http:// or https:// before the domain to avoid this behavior.

Amazing app by the way!

**Comment by ShaneIsrael** [comment]
@turnercore This is good to know, thank you for bringing it up. I'll try to get a fix out for this as soon as I can.

**Comment by ShaneIsrael** [comment]
Hmm. In my testing, there doesn't seem to be an issue. 

If I have my settings like such. 
![image](https://github.com/ShaneIsrael/fireshare/assets/1677199/a8f14778-39ba-441b-9fc1-a99a7669572a)

The generated links when I click any of the "link share" buttons show up like this. 

`https://my.domain.dev/w/adba5e61c991b4bbe11dbc5c56ee1c89`

which includes the 'https'. 

Maybe I'm misunderstanding the problem?

**Comment by turnercore** [comment]
Ahh, I originally set the "sharable link domain" without the https:// because the ENV variable says not to put it in so I thought it would be the same. Are the links generated when the videos are added to the database? Now I've changed the shareable link domain to include the https:// but all links are still not using the https:// when generated (even for newly uploaded videos as I just tested). Not sure what's going on. 

I'm using the unraid container, the ENV domain environment is excluding the https:// and the sharable link used to exclude it, but adding it later isn't changing the links being generated.

**Comment by turnercore** [comment]
As an update to this, I changed the name to something completely different, saved, and changed it back with the https:// and it is now adding it. Very odd. It seems like it works, I'd probably update it to always include https:// unless http:// was in front of that string in the sharable link domain, defaulting to the domain env variable, if I get time to dig into the code maybe I'll do a pull request with that small change. Thanks for checking it out!

**Comment by ShaneIsrael** [comment]
> As an update to this, I changed the name to something completely different, saved, and changed it back with the https:// and it is now adding it. Very odd. It seems like it works, I'd probably update it to always include https:// unless http:// was in front of that string in the sharable link domain, defaulting to the domain env variable, if I get time to dig into the code maybe I'll do a pull request with that small change. Thanks for checking it out!

Any changes you make to settings will take a couple minutes to apply and show up. So if you change the shareable link domain and then immediately try a link its going to use the old settings. Wait like 5 minutes and then try and it should be using the new settings. 

These links are generated on the fly and not saved to the database. So if you change the shareable link domain, your old videos will give you a link using the newly updated domain.

**Comment by ShaneIsrael** [comment]
> I'm using the unraid container, the ENV domain environment is excluding the https:// and the sharable link used to exclude it, but adding it later isn't changing the links being generated.

The ENV domain variable is different from the shareable link domain. The env variable needs to NOT have the https:// since its injected into the metadata so that opengraph works across apps/sites where you share your videos. So you are using that correctly but that env variable is not used at all in generating your links. 

Fireshare's frontend generates the link based off the domain the site is running at. Shareable Link domain is simply a way to override that. 

For example, maybe you have 2 different domains pointing to fireshare. A private domain that you only access and a public domain that everyone else accesses. You could set the sharebale link domain to the public domains address so that anytime you or anyone copies a link while visiting from your private domain, they get links generated with the public domain instead.

**Comment by ShaneIsrael** [comment]
> Yeah, I had the same problem, but I fixed it like this:
> 
>     1. Adding the ENV for my domain without HTTP/HTTPS (Restart needed after changing)
> 
>     2. Adding HTTPS in the Shareable Link Domain in the WebGui (Restart or waiting 5 minutes)
> 
> 
> (the reboots might've been unnecessary)
> 
> This might be a little unrelated, but I think it fits here too, in the docker-compose.yml file in the repository:
> 
> The ENV DOMAIN has double quotes, but putting down your domain in double quotes breaks OpenGraph. Here's what happens if you use DOMAIN="domain.tld" instead of DOMAIN=domain.tld
> The double quotes get replaced with `&#34;` instead of deleting them.

Ah yes, definitely don't add quotes around the ENV domain variable. That is my bad. I'll update the docker-compose file to reflect that.
