### ISSUE TITLE
Video link broken after moving directories

### ISSUE THREAD

**Issue by Korgen1** [ShaneIsrael/fireshare#256]
**Describe the bug**

Moving videos to a different directory ends up creating broken links

**To Reproduce**
1. Upload a video to the fireshare video directory
3. move that video to a different subfolder, or delete/copy it
4. scan library

**Expected behavior**
The video should be linked properly, instead it seems to use the old link despite that link now returning a 404, and the video is unplayable

**Desktop (please complete the following information):**
 - Browser: Vivaldi

**Additional context**

The issue persists no matter what I have tried.

I tried fully deleting the videos from Fireshare itself, and then re-uploading, it still uses the same dead video link.
I also tried deleting the videos and then restarting the fireshare instance, when uploading the videos, it won't generate the link to the new directory.

**Comment by Korgen1** [comment]
Seems like I was able to reach a temporary fix by deleting the files corresponding to the dead video links in /dev_root/fireshare_processed/video_links/

**Comment by ShaneIsrael** [comment]
Yes, the way fireshare works it does not expect your videos to move. It will always generate the same unique link for a video even if you re-upload it or even put it in a different folder. 

So if you want to move your videos you can, but you then need to go into Fireshare and delete the entries labeled "missing" via the user interface. That way the records for those old entries get removed from the database correctly.
