### ISSUE TITLE
Any chance for running outside of Docker?

### ISSUE THREAD

**Issue by Coldblackice** [ShaneIsrael/fireshare#260]
Any possible chance for a Docker-less version?

I have so many game clips I've wanted to share with others but the hassle of uploading them to platforms has been too large a hassle to bother dealing with, and that's on top of clips already being at the mercy of said platforms' encoders, resolutions, framerates, and speeds.

This repo is the solution I didn't know I needed.

The only issue, however, is the Docker requirement, which sadly requires Hyper-V/Virtual-Machine-Platform/virtualization enabled, which unfortunately are known to impact game performances.

**Comment by ShaneIsrael** [comment]
Unfortunately no. This will never be updated to run outside of docker. Docker is basically a standard these days when it comes to running live services. It sounds like you are trying to run this on the same PC that you are playing games on, I would recommend setting up a separate PC/server that runs Fireshare and houses your clips. It doesn't even need to be a very powerful computer, you'd be able to get away with using something as basic as a Raspberry PI.
