### ISSUE TITLE
Does it only support port 443?

### ISSUE THREAD

**Issue by WYithal** [ShaneIsrael/fireshare#261]
**Describe the bug**
The link in the Open Graph seems to have lost the domain port.
![Picture_2024-09-05_15-11-40](https://github.com/user-attachments/assets/7bc276f2-0e0f-4ff7-87d9-9d4f4c644581)

**Comment by ShaneIsrael** [comment]
You should be using a reverse proxy to send traffic to the fireshare container.  You can use whatever port you want for your traffic as long as you set it up behind a reverse proxy.
