### ISSUE TITLE
After uploading a large video it doesn't show up in Fireshare

### ISSUE THREAD

**Issue by OfficialMikeJ** [ShaneIsrael/fireshare#263]
**Describe the bug**
Not sure if this is a bug or if my file is too large or if there's a setting or option I didn't add to the .yml file but I attempted to upload a 4.5GB video from Escape from tarkov gameplay I had on my PC as a test upload and after the upload finished I didn't see it anywhere in Fireshare.

**To Reproduce**
1. Tried uploading the file multiple times 
2. Refreshed the page & waited 5-10 minutes
3. Tried logging into another browser
4. Restarted Fireshare in Docker/Portainer

**Expected behavior**
I Expected to see the video and to be able to play it back and share it with my friends. Wanted to test & make sure that the file would be show up and it did not.

**Screenshots**
No screenshots are available to show what happened.

**Desktop (please complete the following information):**
 - Used Chrome, Brave & Microsoft Edge.

**Additional context**
The file was around 4.5GB in size and was the only file I had that I could use to test to upload and see if it was actually showing in the video section.

**Comment by ShaneIsrael** [comment]
You'll first want to check the docker logs to see if there was any issues / errors with scanning that particular video. 

The size of the video shouldn't matter, but the file type and encoding of the video will matter. Please look at the FAQ section on the readme of this repo and make sure you're video is following those guidelines. 

If it is, and its still not showing up. The best way I can help you is for you to post the docker logs that show up after your upload has finished, and after initiating a manual scan completes.

**Comment by ShaneIsrael** [comment]
Closing due to no response.
