### ISSUE TITLE
Add ability to delete files

### ISSUE THREAD

**Issue by ShaneIsrael** [ShaneIsrael/fireshare#35]
- Allow deletion of a file after a confirmation dialog
- Remove the files data from the database
- Remove all the generated data that exists for the file

**Comment by pngmn** [comment]
A library scan should also remove db entries from videos that were deleted from disk.

**Comment by ShaneIsrael** [comment]
@pngmn We don't want to do that because that causes major issues if your ran firebase and forgot to mount your videos directory, it would effectively wipe your database clean. So the database is the source of truth rather than the files themselves. That's just one example, in my case all of my videos are on a network drive, if that network drive failed to mount for whatever reason it Firebase would just see that I no longer have any video files and would wipe the db clean. 

So with that being said, what Firebase will do is mark files as available/missing, and report those missing files to you in the web app. From there, you will be able to choose to delete the missing file data for good from the database.

**Comment by ShaneIsrael** [comment]
Added in PR #62
