### ISSUE TITLE
docker-compose error?

### ISSUE THREAD

**Issue by playitforless** [ShaneIsrael/fireshare#47]
Not sure if it was just me but I had to change the line 

`image: fireshare:latest` to `image: shaneisrael/fireshare:latest`

as I was getting the following error but works great after changing that line.

> ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

It's working great now, looking forward to trying it out.

**Comment by ShaneIsrael** [comment]
Oh thank you for catching that. When testing locally I tag it as fireshare:latest and had forgotten to add my dockerhub repo to the front.
