### ISSUE TITLE
can't copy timelink

### ISSUE THREAD

**Issue by lordfiSh** [ShaneIsrael/fireshare#49]
If I click on the Time link Icon nothing happens, 
this shows up in the console: ![image](https://user-images.githubusercontent.com/389680/172171565-9eb583b0-e5a8-41d6-bb88-62368b5c6b9c.png)

**Comment by Shane-stage** [comment]
Looking into this a little bit, it seems that writing to the clipboard only works under a secure https protocol. If you set the server up under https it should work. Is it only the time stamped link that fails with this error or does the regular link share button also cause the same error?

**Comment by lordfiSh** [comment]
Vivaldi , but same on Edge. Can test https later... 

Normal Linking works: 
![image](https://user-images.githubusercontent.com/389680/172182974-e669c82a-7df8-4c4d-97f1-5be7d27f74e0.png)

**Comment by Shane-stage** [comment]
Interesting, I think I have a fix for the copying so that it works on non https as well. (I'll try to get that in later today on my lunch or after work). On the 404 issue, can you share the link path its giving you? 

I'm assuming you are running this via docker as well correct? If not, I know why you're getting the 404.

**Comment by lordfiSh** [comment]
The Unraid Docker Container from you ;)

URL: http://192.168.1.54:8682/df6445dcc104a64b128e82b771bd0c10
Copied URL: http://192.168.1.54:8682/#/w/df6445dcc104a64b128e82b771bd0c10

**Comment by Shane-stage** [comment]
Oh yes I see it now. Its the copy button the the /w/ page that is broken.

Thank you for pointing both of these issue out. I'll try to have a fix for them this afternoon. I'll close this issue once I have a fix pushed later.

**Comment by ShaneIsrael** [comment]
Fixed in PR #53
