### ISSUE TITLE
Read Metadata + Filters & Tags

### ISSUE THREAD

**Issue by lordfiSh** [ShaneIsrael/fireshare#50]
Would be cool if you would read the Metadata of the Recordings, eg Windows Game Bar save the Game Name and Recoding Date. 
Also if newly imported Videos would get the a Tag "unsorted" or something that would be great. 

Just a Idea...

**Comment by ShaneIsrael** [comment]
You can now sort by creation date and title ( PR #66 ). I'm going to close this issue for now but I have noted down the idea of tagging videos as "unsorted" as a potential feature add but I'm going to do a bit more thinking on whether "tags" are the best way to go about it.
