### ISSUE TITLE
Sorting by date added or newest

### ISSUE THREAD

**Issue by geekedtv** [ShaneIsrael/fireshare#51]
First off, wonderful app! I'll be doing a full review on my website soon. I had the idea to use this to share videos of my kids to their grandparents and family.

Would love the ability for them to be able to sort videos by newest or recently added.

**Comment by ShaneIsrael** [comment]
@geekedtv Yes this is one of the next features I will be working to add (I also want to sort my stuff haha). It might not make it out until this weekend though so I hope that is okay.

**Comment by geekedtv** [comment]
> @geekedtv Yes this is one of the next features I will be working to add (I also want to sort my stuff haha). It might not make it out until this weekend though so I hope that is okay.

Awesome! Looking forward to it and I can wait for sure!

**Comment by ShaneIsrael** [comment]
Added in PR #66
