### ISSUE TITLE
OpenGraph Embed

### ISSUE THREAD

**Issue by duplaja** [ShaneIsrael/fireshare#54]
Hello!

I wanted to say that I love this project so far!

One small thing: I don't seem to be having any luck with the OpenGraph embed . 

I'm seeing just a generic embed (see attached). Is there something I'm missing?

![embed](https://user-images.githubusercontent.com/20245408/172228706-167f54a9-7cf8-4a43-8fa5-add0f22cf0ef.png)

**Comment by Talon876** [comment]
What URL are you trying to share? The OpenGraph data will only work with URLs starting with `/w/` (not `/#/w/`). E.g. https://v.fireshare.net/w/e94ee15ac9f8b56e415ae784ef114e09

**Comment by duplaja** [comment]
I'm not quite sure how I got the link with the /#/ in it, thought I'd just used the share button, but that was the issue. Thank you!

**Comment by ShaneIsrael** [comment]
@duplaja You might have copied the link from the url bar. The share buttons will give you the /w/ link but that link gets redirected to /#/w/ which you may not have noticed. 

Glad it's working!
