### ISSUE TITLE
An API to allow Sharex to Post to Fireshare

### ISSUE THREAD

**Issue by geekedtv** [ShaneIsrael/fireshare#55]
This one is a bit of a stretch. I use ShareX to record desktop videos and it has options to auto upload to different hosts. I'd love to be able to auto upload the MP4 clips to Fireshare. https://github.com/ShareX/ShareX

**Comment by ShaneIsrael** [comment]
This could potentially be explored if we end up building in the ability to allow uploading. This isn't something on the immediate priority list though unfortunately. But I will keep it in mind.

**Comment by Talon876** [comment]
@geekedtv not sure if this would work for you, but you could start an SFTP server with your video folder also mounted in to it. Then configure ShareX to SFTP your videos to the SFTP server, where fireshare would then also be able to see them.

![image](https://user-images.githubusercontent.com/926585/172264890-27395cf9-cacc-4c44-b7f6-ef55ee332a1c.png)

**Comment by geekedtv** [comment]
> @geekedtv not sure if this would work for you, but you could start an SFTP server with your video folder also mounted in to it. Then configure ShareX to SFTP your videos to the SFTP server, where fireshare would then also be able to see them.
> 
> ![image](https://user-images.githubusercontent.com/926585/172264890-27395cf9-cacc-4c44-b7f6-ef55ee332a1c.png)

I could just mount the video folder to the ShareX media folder just as easy :)

I thought of this after I made this request lol.
