### ISSUE TITLE
one button to add all videos to public feed

### ISSUE THREAD

**Issue by kjames2001** [ShaneIsrael/fireshare#58]
Great app! will see myself using it often!

However, please add a button to add all videos to public feed. Thanks.

**Comment by ShaneIsrael** [comment]
Toggle selection wouldn't really provide any benefit over the current system which is based off a simple toggle button on each card/list. 

I'm not sure if a blanket "add all" button is a good but we have considered adding a configuration option to allow you to choose the default privacy setting for newly added videos.

**Comment by kjames2001** [comment]
is each subfolder considered a list? then i dont see a toggle for it. otherwise what @geekedtv suggested would also be a good idea.

**Comment by kjames2001** [comment]
on a side note, is there anyway to remove the bottom bar? or customize it?

**Comment by benborges** [comment]
Would be neat for my usecase to be able to define on the .env file if the videos are public or not, because when you handle hundreds or thousands of videos, going manually one by one to enable public view is quite some friction, thanks for working on this feature no matter how it goes, it's going to be a great feature !

**Comment by ShaneIsrael** [comment]
@benborges There is a setting that you can set in the config.json file for the default privacy. Set it to true and any new videos fireshare scans in will be set to public. 

The config.json file is located in the directory you mapped as the fireshare data directory.

**Comment by benborges** [comment]
Thanks very much i have found this setting, for now it's perfect for my usecase, thanks again !

**Comment by ShaneIsrael** [comment]
I have added this to the feature suggestions section our our wiki here: https://github.com/ShaneIsrael/fireshare/wiki
