### ISSUE TITLE
Feature Request: Ability to upload files through browser

### ISSUE THREAD

**Issue by AliMickey** [ShaneIsrael/fireshare#65]
Ability to upload files through browser

This would allow an instance to be used with a group of friends to share clips.

Accompanied with uploader name if this doesn't exist already?

**Comment by AliMickey** [comment]
Yeah, i've thought of that, but then I need to host a different service to allow uploading via web to the local folder. 

I just found out that this is using Flask which I am very familiar with. I will definitely try and implement something when I get the chance.

**Comment by ShaneIsrael** [comment]
Add the folders to Google Drive and share them. Your friends would upload to your google drive folder, which would sync the files down to your PC running Fireshare. This just requires you to set up google drive sync, but makes the uploading process for your friends super easy.

**Comment by AliMickey** [comment]
That would still not be as streamlined as a built in upload.

**Comment by ShaneIsrael** [comment]
I'm only trying to give you semi decent workarounds that would work and be fairly painless. 

The problem is that adding upload capability for other users besides the admin requires a bit of work and the feature itself falls outside of the core concept that Fireshare is built for. Peertube is more akin to a solution to your specific use case. 

Uploading that supports multiple user accounts might be something that gets added in the far future but is not something that we'll be working on anytime soon because it just doesn't align with what we are trying to accomplish.

**Comment by Write** [comment]
An other idea is to use filebrowser inside a container and mount only needed directory. https://filebrowser.org/installation
It also support multiples users and comes with a permissions system so it's pretty awesome. 
I only use it for myself and added fireshare video folder, it works great to upload easily !

**Comment by ShaneIsrael** [comment]
@Write This is an awesome solution that I may actually implement myself on my server.

**Comment by AliMickey** [comment]
> I'm only trying to give you semi decent workarounds that would work and be fairly painless.
> 
> The problem is that adding upload capability for other users besides the admin requires a bit of work and the feature itself falls outside of the core concept that Fireshare is built for. Peertube is more akin to a solution to your specific use case, I would check it out.
> 
> Uploading that supports multiple user accounts might be something that gets added in the far future but is not something that we'll be working on anytime soon because it just doesn't align with what we are trying to accomplish.

You do you, but PeerTube comes with unnecessary features for this use case.

In any case, I will implement a simple upload feature, the UI of Fireshare is better than existing projects and I personally would like to use it more than just a simple file viewer. Even Filebrowser (I use it for other purposes) is not a good alternative, as users need to visit two separate websites to accomplish basic video upload.

What you do with the PR is up to you. But I will definitely be making use of it on my own (as many others will be as well I'm sure).

Thanks for the cool project!

**Comment by ShaneIsrael** [comment]
> > I'm only trying to give you semi decent workarounds that would work and be fairly painless.
> > The problem is that adding upload capability for other users besides the admin requires a bit of work and the feature itself falls outside of the core concept that Fireshare is built for. Peertube is more akin to a solution to your specific use case, I would check it out.
> > Uploading that supports multiple user accounts might be something that gets added in the far future but is not something that we'll be working on anytime soon because it just doesn't align with what we are trying to accomplish.
> 
> You do you, but PeerTube comes with unnecessary features for this use case.
> 
> In any case, I will implement a simple upload feature, the UI of Fireshare is better than existing projects and I personally would like to use it more than just a simple file viewer. Even Filebrowser (I use it for other purposes) is not a good alternative, as users need to visit two separate websites to accomplish basic video upload.
> 
> What you do with the PR is up to you. But I will definitely be making use of it on my own (as many others will be as well I'm sure).
> 
> Thanks for the cool project!

If what you implement is a simple upload for an authenticated administrator account then I'm fine with with merging it so long as the server code as well as the front end implementation checked by us and deemed acceptable. Anything more complicated than that (support for other user accounts, etc) I will not merge. 

I need to properly think about how to best implement support for additional users and what that means for the database model as well as much of the logic that would need to be updated to support additional user profiles. This is something that may be added a ways down the line, it just needs a lot of thought on how best to implement.
