### ISSUE TITLE
Streaming issues

### ISSUE THREAD

**Issue by Chocolate-Banana** [ShaneIsrael/fireshare#74]
Hi

Great app btw! Just could do with some advise regarding nginx settings. Are there any that can help with buffering? 

I currently have 55mb upload speed with 15 second clips, I'm surprised people out my network experience buffering issues. The file sizes are 180mb max but mostly under 100mb and are MP4 files. 

I'm assuming it's an nginx setting for caching which would help resolve. 

Any help would be appreciated :)

**Comment by ShaneIsrael** [comment]
There's a chance this could be a bug with the Fireshare nginx config. To help figure that out could I have you post 2 screenshots. 

One of a https://www.speedtest.net/ upload/download result. 

And another showing the file sizes of the clips/videos you are having issues with.

Thank you!
