### ISSUE TITLE
[Feature Request] Basic video editing (cropping, cutting)

### ISSUE THREAD

**Issue by Pheggas** [ShaneIsrael/fireshare#96]
Hello. First of all, thank you for amazing project you've made. It's very pleasing for eyes, it's responsive, have neat features. It also has it's downsides like some bugs but i think those will be fixed ASAP :) 

I'd like to see basic video editing tool right in the Web UI. I mean the basic functions like cropping or cutting some moments. Will it be possible? 

Thanx.

**Comment by ShaneIsrael** [comment]
@Pheggas Please do not create feature requests and label them as a "bug". 

First of all, you've already created a feature request a week ago asking about basic video editing here: #81 to which I responded. 

Making multiple requests for the same feature is not going to make a feature request happen faster. This is a completely free software. It's open source and we are not paid to work on it. Given that, it may be months before we get to a particular feature and that's _if_ we also deem it worthwhile to add. 

Video editing, even basic is a lot more complicated than you might think. Just that one feature would take a lot of time and effort to get it right and currently falls outside of the scope of what Fireshare is set out to accomplish. That isn't to say it won't ever be added, its just very low on the priority list of what we need/want to work on.

That being said, Fireshare is open source. You are completely welcome and even encouraged to aid in its development. See this section on contributing: https://github.com/ShaneIsrael/fireshare#contributing

**Comment by Pheggas** [comment]
Sorry, i didn't realise i already created one feature request. Closing.
