### ISSUE TITLE
Feature req: handbrake in a container and queuing 

### ISSUE THREAD

**Issue by Orionx86** [ShaneIsrael/fireshare#99]
There is mention of using handbrake out of band. It might be a neat feature to add in handbrake as an additional container service. There’s a long history of automating it with python and you can probably leverage the built in queue.

**Comment by ShaneIsrael** [comment]
@Orionx86 My only worry is that it would be too taxing on the system unless there was GPU support tied in. This is definitely worth exploring though.

**Comment by ShaneIsrael** [comment]
I have added this to the feature suggestions section our our wiki here: https://github.com/ShaneIsrael/fireshare/wiki
